-   id: issue-prefix
    name: Add issue as commit message prefix
    description: Searches the branch name for something looking like a jira issue name and prepends the commit message with it. Supports default issue.
    entry: issue-prefix
    language: python
    always_run: true
    stages: [prepare-commit-msg]
